/**
 * Run once to seed the global posModules collection in Firestore.
 * Usage: npx ts-node scripts/seedModules.ts
 * Requires GOOGLE_APPLICATION_CREDENTIALS env var pointing to a service account key.
 */
import * as admin from 'firebase-admin';

admin.initializeApp();
const db = admin.firestore();

const modules = [
  {
    id: 'fast_checkout',
    name: 'Fast Checkout',
    tagline: 'Quick-add, parked bills, and keyboard shortcuts for faster billing',
    description: 'Enables quicker and more effective checkout experience with hot-key navigation, repeat-last-bill, and top-item shortcuts.',
    icon: 'Zap',
    category: 'pos',
    monthlyPrice: 299,
    yearlyPrice: 2990,
    includedInPlans: ['starter', 'growth', 'pro'],
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'returns_exchanges',
    name: 'Easy Returns & Exchanges',
    tagline: 'Manage and track all product returns and exchanges',
    description: 'Helps manage and keep track of the total number of order returns and exchanges with automatic stock restocking.',
    icon: 'RotateCcw',
    category: 'pos',
    monthlyPrice: 349,
    yearlyPrice: 3490,
    includedInPlans: ['growth', 'pro'],
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'loyalty',
    name: 'Loyalty & Memberships',
    tagline: 'Reward customers with points and tiered membership benefits',
    description: 'Enables the creation and management of loyalty and membership programs for customers with configurable tiers.',
    icon: 'Star',
    category: 'customers',
    monthlyPrice: 499,
    yearlyPrice: 4990,
    includedInPlans: ['growth', 'pro'],
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 'multiple_payment_modes',
    name: 'Multiple Payment Modes',
    tagline: 'Accept split payments across cash, UPI, card and more',
    description: 'Supports a variety of payment methods including cash, card, UPI & more in a single bill.',
    icon: 'CreditCard',
    category: 'payments',
    monthlyPrice: 249,
    yearlyPrice: 2490,
    includedInPlans: ['growth', 'pro'],
    isActive: true,
    sortOrder: 4,
  },
  {
    id: 'multiple_billing_counters',
    name: 'Multiple Billing Counters',
    tagline: 'Handle transactions at different counters simultaneously',
    description: 'Enables businesses to handle multiple transactions at different counters simultaneously with per-counter bill tracking.',
    icon: 'Layers',
    category: 'pos',
    monthlyPrice: 299,
    yearlyPrice: 2990,
    includedInPlans: ['growth', 'pro'],
    isActive: true,
    sortOrder: 5,
  },
  {
    id: 'weight_scale',
    name: 'Weight-Scale Integration',
    tagline: 'Auto-read weight from connected scales via USB/Bluetooth',
    description: 'Helps you accurately maintain a complete report of the weight of the goods/products via Web HID API.',
    icon: 'Scale',
    category: 'pos',
    monthlyPrice: 299,
    yearlyPrice: 2990,
    includedInPlans: ['pro'],
    isActive: true,
    sortOrder: 6,
  },
  {
    id: 'cash_tender',
    name: 'Cash Tender',
    tagline: 'Instant change calculation with denomination quick-buttons',
    description: 'It enables cashiers to correctly and quickly execute cash transactions with automatic change calculation.',
    icon: 'Banknote',
    category: 'payments',
    monthlyPrice: 149,
    yearlyPrice: 1490,
    includedInPlans: ['growth', 'pro'],
    isActive: true,
    sortOrder: 7,
  },
  {
    id: 'cash_drawer',
    name: 'Cash Drawer Integration',
    tagline: 'Auto-open cash drawer on every cash transaction',
    description: 'It enables the automatic opening and closing of a cash drawer during cash transactions via Web Serial API.',
    icon: 'Archive',
    category: 'pos',
    monthlyPrice: 99,
    yearlyPrice: 990,
    includedInPlans: ['starter', 'growth', 'pro'],
    isActive: true,
    sortOrder: 8,
  },
  {
    id: 'whatsapp_integration',
    name: 'WhatsApp Integration',
    tagline: 'Send digital receipts, feedback links, and loyalty updates via WhatsApp',
    description: 'Allows for automated communication with customers through WhatsApp for receipts, reminders, and feedback.',
    icon: 'MessageCircle',
    category: 'customers',
    monthlyPrice: 399,
    yearlyPrice: 3990,
    includedInPlans: ['starter', 'growth', 'pro'],
    isActive: true,
    sortOrder: 9,
  },
  {
    id: 'customer_feedback',
    name: 'Customer Feedback',
    tagline: 'Collect star ratings and reviews after every sale',
    description: 'Enables customers to directly leave their honest reviews/feedback through digital receipts and WhatsApp links.',
    icon: 'MessageSquare',
    category: 'customers',
    monthlyPrice: 199,
    yearlyPrice: 1990,
    includedInPlans: ['growth', 'pro'],
    isActive: true,
    sortOrder: 10,
  },
  {
    id: 'in_store_online_orders',
    name: 'In-Store & Online Orders',
    tagline: 'Manage both walk-in and online orders from a single screen',
    description: 'Helps to manage both online and offline business easily from one unified order queue.',
    icon: 'ShoppingCart',
    category: 'operations',
    monthlyPrice: 499,
    yearlyPrice: 4990,
    includedInPlans: ['pro'],
    isActive: true,
    sortOrder: 11,
  },
  {
    id: 'multi_bill_tabs',
    name: 'Multiple Billing At Single Time',
    tagline: 'Run up to 5 simultaneous open bills in parallel tabs',
    description: 'It enables a cashier to process multiple transactions simultaneously with tab-based bill management.',
    icon: 'Columns',
    category: 'pos',
    monthlyPrice: 199,
    yearlyPrice: 1990,
    includedInPlans: ['pro'],
    isActive: true,
    sortOrder: 12,
  },
  {
    id: 'offline_pos',
    name: 'Offline POS',
    tagline: 'Keep billing even without internet, auto-syncs when reconnected',
    description: 'Offline POS works without internet, automatically syncing data to the cloud when reconnected, on desktop and mobile.',
    icon: 'WifiOff',
    category: 'operations',
    monthlyPrice: 599,
    yearlyPrice: 5990,
    includedInPlans: ['pro'],
    isActive: true,
    sortOrder: 13,
  },
  {
    id: 'vpay',
    name: 'V Pay',
    tagline: 'Instant UPI QR on screen for customers to scan and pay',
    description: 'When a retailer starts a UPI transaction, a QR code instantly appears on the device, allowing customers to scan and pay with ease.',
    icon: 'QrCode',
    category: 'payments',
    monthlyPrice: 199,
    yearlyPrice: 1990,
    includedInPlans: ['starter', 'growth', 'pro'],
    isActive: true,
    sortOrder: 14,
  },
  {
    id: 'vcheckout',
    name: 'V-Checkout',
    tagline: 'Let customers scan products on their phone and pay themselves',
    description: 'V-Checkout lets customers scan products using their mobile, add to cart, and pay securely, reducing queues and faster checkout.',
    icon: 'Smartphone',
    category: 'pos',
    monthlyPrice: 799,
    yearlyPrice: 7990,
    includedInPlans: ['pro'],
    isActive: true,
    sortOrder: 15,
  },
  {
    id: 'image_based_pos',
    name: 'Image Based POS',
    tagline: 'Large product image tiles for touch-friendly fast billing',
    description: 'This feature displays Product images to help quickly identify items, speed up billing, and ensure a smooth checkout.',
    icon: 'Image',
    category: 'pos',
    monthlyPrice: 199,
    yearlyPrice: 1990,
    includedInPlans: ['pro'],
    isActive: true,
    sortOrder: 16,
  },
];

async function seed() {
  console.log('Seeding posModules collection...');
  const batch = db.batch();
  for (const mod of modules) {
    const { id, ...data } = mod;
    const ref = db.collection('posModules').doc(id);
    batch.set(ref, { ...data, createdAt: admin.firestore.FieldValue.serverTimestamp() }, { merge: true });
    console.log(`  ✓ ${id}`);
  }
  await batch.commit();
  console.log(`Done! Seeded ${modules.length} modules.`);
  process.exit(0);
}

seed().catch(err => { console.error(err); process.exit(1); });
