import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Hub } from '../firebase';

export const generateHubPDF = (hub: Hub) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;

  // Header
  doc.setFillColor(21, 66, 18); // Primary color #154212
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(`${hub.name} Official Crop Guide`, margin, 20);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('KrishiDukan Agronomy Series - Official Documentation', margin, 30);

  // Summary Section
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Crop Overview', margin, 55);
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  const taglineLines = doc.splitTextToSize(hub.tagline, pageWidth - (margin * 2));
  doc.text(taglineLines, margin, 65);

  // Quick Stats Table
  autoTable(doc, {
    startY: 75,
    margin: { left: margin, right: margin },
    head: [['Ideal Climate', 'Soil Type', 'Water Needs', 'Best Season']],
    body: [[
      hub.idealClimate || 'Tropical',
      hub.soilType || 'Loamy',
      hub.waterNeeds || 'Moderate',
      hub.bestSeason || 'Spring'
    ]],
    theme: 'grid',
    headStyles: { fillStyle: 'F', fillColor: [21, 66, 18], textColor: [255, 255, 255], fontStyle: 'bold' },
    styles: { fontSize: 10, cellPadding: 5 }
  });

  // Growth Stages
  if (hub.growthStages && hub.growthStages.length > 0) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Growth Journey & Recommendations', margin, (doc as any).lastAutoTable.finalY + 15);

    autoTable(doc, {
      startY: (doc as any).lastAutoTable.finalY + 22,
      margin: { left: margin, right: margin },
      head: [['Phase', 'Duration', 'Description', 'Recommended Products']],
      body: hub.growthStages.map(stage => [
        stage.phase,
        stage.duration,
        stage.description,
        stage.products.join(', ')
      ]),
      theme: 'striped',
      headStyles: { fillColor: [112, 90, 76] }, // Secondary color #705a4c
      styles: { fontSize: 9, cellPadding: 4 }
    });
  }

  // Nutrition & Advisory
  const advisoryY = (doc as any).lastAutoTable.finalY + 15;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Expert Advisory', margin, advisoryY);
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(hub.advisory.title, margin, advisoryY + 8);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const advisoryLines = doc.splitTextToSize(hub.advisory.description, pageWidth - (margin * 2));
  doc.text(advisoryLines, margin, advisoryY + 15);

  // Common Mistakes
  if (hub.commonMistakes && hub.commonMistakes.length > 0) {
    const mistakesY = advisoryY + 25 + (advisoryLines.length * 5);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(200, 0, 0);
    doc.text('Mistakes to Avoid (Pro Tips)', margin, mistakesY);
    
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(10);
    hub.commonMistakes.forEach((mistake, index) => {
      const mistakeLines = doc.splitTextToSize(`• ${mistake}`, pageWidth - (margin * 2.5));
      doc.text(mistakeLines, margin + 5, mistakesY + 10 + (index * 12));
    });
  }

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by KrishiDukan Official Platform - ${new Date().toLocaleDateString()}`, margin, doc.internal.pageSize.getHeight() - 10);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin - 20, doc.internal.pageSize.getHeight() - 10);
  }

  doc.save(`KrishiDukan_${hub.name}_Guide.pdf`);
};
