export const CROPS = [
  { name: "Grapes / द्राक्ष / अंगूर", emoji: "🍇" },
  { name: "Onion / कांदे / प्याज", emoji: "🧅" },
  { name: "Banana / केळी / केला", emoji: "🍌" },
  { name: "Watermelon / कलिंगड / तरबूज", emoji: "🍉" },
  { name: "Groundnut / भुईमूग / मूंगफली", emoji: "🥜" },
  { name: "Vegetables / भाजीपाला / सब्ज़ियाँ", emoji: "🥦" },
  { name: "Pomegranate / डाळिंब / अनार", emoji: "🍎" },
  { name: "Cotton / कापूस / कपास", emoji: "🌿" },
];

export const BENEFITS = [
  {
    icon: "💧",
    en: "Drought Resistance",
    hi: "सूखा प्रतिरोध",
    mr: "पाण्याचा ताण सहन करण्याची क्षमता",
    desc_en: "Significantly increases the plant's ability to withstand water stress and drought — critical for India's erratic monsoons.",
    desc_hi: "पौधों की पानी की कमी और सूखे को सहन करने की क्षमता बढ़ाता है — भारत के अनिश्चित मानसून के लिए अत्यंत उपयोगी।",
    desc_mr: "पाण्याची कमतरता आणि दुष्काळाचा सामना करण्याची वनस्पतीची क्षमता वाढवते — महाराष्ट्राच्या अनियमित पावसासाठी अत्यंत आवश्यक.",
  },
  {
    icon: "✨",
    en: "Premium Fruit Quality",
    hi: "फलों की प्रीमियम गुणवत्ता",
    mr: "फळांचा आकर्षक रंग, चमक व वजन",
    desc_en: "Fruits get better color, shine, and weight. Premium produce sells for higher prices in the market.",
    desc_hi: "फलों को बेहतर रंग, चमक और वजन मिलता है — बाज़ार में ज़्यादा दाम मिलते हैं।",
    desc_mr: "फळांना उत्तम रंग, चमक आणि वजन मिळते — बाजारात जास्त भाव मिळवून देते.",
  },
  {
    icon: "🛡️",
    en: "Disease Resistance",
    hi: "रोग प्रतिरोधक शक्ति",
    mr: "रोगप्रतिकारक क्षमता वाढते",
    desc_en: "Boosts the crop's natural immunity against fungal and bacterial diseases, reducing chemical spray costs.",
    desc_hi: "फसल की रोगों के खिलाफ प्राकृतिक प्रतिरोधक क्षमता बढ़ाता है, रासायनिक स्प्रे का खर्च कम होता है।",
    desc_mr: "रोग आणि बुरशीपासून स्वतःचे संरक्षण करण्याची क्षमता वाढते, फवारणीचा खर्च कमी होतो.",
  },
  {
    icon: "🌱",
    en: "Stronger Roots & Richer Soil",
    hi: "मज़बूत जड़ें और समृद्ध मिट्टी",
    mr: "मुळांची निर्मिती व सेंद्रिय कर्बाचे प्रमाण वाढते",
    desc_en: "Promotes deep root formation, increases soil organic matter, and builds long-term soil health.",
    desc_hi: "गहरी जड़ें बनने में मदद करता है, मिट्टी में कार्बनिक पदार्थ बढ़ाता है।",
    desc_mr: "खोलवर मुळे जाण्यास मदत करते आणि जमिनीत सेंद्रिय कर्बाचे प्रमाण वाढवते.",
  },
  {
    icon: "⏳",
    en: "Longer Shelf Life",
    hi: "लंबी शेल्फ लाइफ",
    mr: "फळे अधिक दिवस टिकतात",
    desc_en: "Produce lasts longer after harvest — reducing post-harvest losses and improving market price realization.",
    desc_hi: "कटाई के बाद उपज अधिक समय तक ताज़ी रहती है — नुकसान कम होते हैं।",
    desc_mr: "काढणीनंतर फळे जास्त काळ ताजी राहतात — नुकसान कमी होते.",
  },
  {
    icon: "🍬",
    en: "Higher Sugar & Sweetness",
    hi: "अधिक मिठास",
    mr: "साखर चांगल्या प्रकारे तयार होऊन गोडी वाढते",
    desc_en: "Helps fruits and vegetables develop higher natural sugar content — tastier, more marketable produce.",
    desc_hi: "फलों और सब्ज़ियों में प्राकृतिक शर्करा बढ़ती है — ज़्यादा स्वादिष्ट और बिकने योग्य उपज।",
    desc_mr: "नैसर्गिक साखरेचे प्रमाण वाढल्याने गोडी वाढते — मालाला जास्त मागणी येते.",
  },
];
